clc
clear all
%format long
format short eng
%========== GENETIC  PARAMETER =====================
NS=100;
NG=1000;
NP=4;
NN=1;

RC=.99;
PR=.1;
PM=.1;
PC=.9999;
AU(1)=25;AL(1)=7;
AU(2)=.02;AL(2)=.01;
AU(3)=550;AL(3)=350;
AU(4)=.4;AL(4)=.2;
NSPR=round(NS*PR);
%=====================================
DATACONDUC(1)=14.1;         % K1
DATACONDUC(2)=.0166;      % K2
DATACONDUC(3)=0.;           % K3
DATACONDUC(4)=448.;         % CP1
DATACONDUC(5)=.291;       % CP2
DATACONDUC(6)=.0;           % CP3
DATACONDUC(7)=10.^5;        % Ro
DATACONDUC(8)=120.;         % QLCK
DATACONDUC(9)=300.;         % T Initial
DATACONDUC(10)=5;           % Error
DATACONDUC(11)=100;         % NT
DATACONDUC(12)=16;          % NX
DATACONDUC(13)=16;          % Ny
DATACONDUC(14)=DATACONDUC(1)/(DATACONDUC(7)*DATACONDUC(4));
DATACONDUC(15)=DATACONDUC(8)*DATACONDUC(1);

T=DIRECTSOLUTION(DATACONDUC);
TE=REFRENCESOLUTION(T,DATACONDUC);

%T=DIRECTSOLUTION(DATACONDUC);
%ARMS=ARMS(T,TE,DATACONDUC)

%GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
NSS=20;
ijk=0;
for KK=1:NSPR
    A=INTITALPOPULATION(TE,DATACONDUC,NSS,NP,NN,AU,AL);
    for K=1:NSS
        A=REALTIVEFITTNESS(A,NSS,NP);
        q=0; q(1:NP)=A(1,1:NP);AVE=A(1,NP+3);MAX=A(2,NP+3); q=[K,q,MAX,AVE];q=q'
        A=TOURNOMENTSELECTION(NSS,NP,A);
        ANEW=CROOSOVER(A,NSS,NP,PC,AU,AL);
        ANEW=MOTTATION(ANEW,AU,AL,PM,NSS,NP);
        ANEW=FITTNESSCACULATION(TE,DATACONDUC,ANEW,NSS,NP,AU,AL);
        ANEW=FINALSELECTION(A,ANEW,NSS,NP,NSPR);
        A=0;A=ANEW;
        ijk=ijk+1;
        DATAPRINT(ijk,1)=ijk;
        if (ijk==1)
            DATAPRINT(ijk,2)=NSS;
        else
            DATAPRINT(ijk,2)=DATAPRINT(ijk-1,2)+NSS;
        end
        DATAPRINT(ijk,3)=AVE;
        DATAPRINT(ijk,4)=MAX;
        DATAPRINT(ijk,4+1:4+NP)=q(1+1:NP+1);

    end
    MEHDIPUB(KK,1:NP)=A(1,1:NP);
    MEHDIPUB(KK,NP+1)=A(1,NP+1);


end
MEHDIPUB
A=INTITALPOPULATION(TE,DATACONDUC,NS,NP,NN,AU,AL);
B=[A;MEHDIPUB];
B=sortrows(B,-(NP+1));
A(1:NS,1:NP+1)=B(1:NS,1:NP+1);

for K=1:NG


    A=REALTIVEFITTNESS(A,NS,NP);
    q=0; q(1:NP)=A(1,1:NP);AVE=A(1,NP+3);MAX=A(2,NP+3); q=[K,q,MAX,AVE];q=q'

    A=TOURNOMENTSELECTION(NS,NP,A)
    ANEW=CROOSOVER(A,NS,NP,PC,AU,AL);
    ANEW=MOTTATION(ANEW,AU,AL,PM,NS,NP);
    ANEW=FITTNESSCACULATION(TE,DATACONDUC,ANEW,NS,NP,AU,AL);
    ANEW=FINALSELECTION(A,ANEW,NS,NP,NSPR);
    A=0;A=ANEW;
    ijk=ijk+1;
    DATAPRINT(ijk,1)=ijk;
    DATAPRINT(ijk,2)=DATAPRINT(ijk-1,2)+NS;
    DATAPRINT(ijk,3)=AVE;
    DATAPRINT(ijk,4)=MAX;
    DATAPRINT(ijk,4+1:4+NP)=q(1+1:NP+1);
   
    save

end
%GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
q
format long eng
